service: crud-api

provider:
  name: google
  runtime: nodejs
  project: crud-api-f5154
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .gcloud/**

functions:
  create:
    handler: create
    events:
      - http: path
  read:
    handler: read
    events:
      - http: path
  update:
    handler: update
    events:
      - http: path
  delete:
    handler: delete
    events:
      - http: path