service:
  name: firestorecrudapi

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  region: europe-west1

  project: "{PROJECT_ID}"
  credentials: ~/.gcloud/{KEYFILE}.json

  runtime: nodejs10
  memorySize: 1024
  timeout: 10s

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .gcloud/**

functions:
  create:
    handler: create
    events:
      - http: create
        method: POST
  read:
    handler: read
    events:
      - http: read
        method: GET
  update:
    handler: update
    events:
      - http: update
        method: POST
  delete:
    handler: delete
    events:
      - http: delete
        method: POST
